### ISSUE TITLE
Fichier manquant pour les tests ?

### ISSUE THREAD

**Issue by joeybara** [guyfrancoeur/INF3135_H2019_TP2#10]
@guyfrancoeur 

Bonjour, pour le test suivant je vois que vous faites référence au data.txt (qui n'est pas présent actuellement dans le tp1-data.zip contrairement au data.zip du TP1, où là il l'était). 

`ls -1 ./data/data.txt`

![ls](https://user-images.githubusercontent.com/33882472/54058875-311f2c00-41c5-11e9-9206-f684063e0d7a.png)

Est-ce une erreur dans les tests ?

Merci

**Comment by guyfrancoeur** [comment]
Allo,

il sera crée par le make data.

**Comment by joeybara** [comment]
@guyfrancoeur Pour être certain, vous allez créer ce fichier ? 

Car présentement, mon `make data` ne le crée pas, il télécharge uniquement les données.

**Comment by onwilliam** [comment]
Bonjour, 

> Lorsqu'on entre make data, le téléchargement des données (fichier) https://www.github.com/guyfrancoeur/INF3135_H2019/raw/master/tp1/data.zip se fait de façon automatique. La décompression du fichier est est dirigée dans répertoire ./data;

La commande `make data` est censé télécharger data.zip (non tp1-data.zip) et décompresser son contenu (data.txt) dans un nouveau répertoire appelé data.

Si le répertoire data et le fichier data.txt existe la commande `ls -l ./data/data.txt` va  retourner 0 et afficher ./data/data.txt avec des informations additionnelles sinon il va dire que le répertoire ou le fichier n'existe pas et retourner un code d'erreur autre que le 0.

**Comment by dbrsseau** [comment]
@onwilliam non! Si tu lis le issue #5 @guyfrancoeur donne belle et bien le nouveau lien vers les nouvelles données données pour la commande `make test`. Il faut utiliser `tp1-data.zip`.

**Comment by joeybara** [comment]
@onwilliam De toute façon, les données du fichier data.zip ne semble plus être téléchargeable.

```
Archive:  data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data.zip or
        data.zip.zip, and cannot find data.zip.ZIP, period.
```
@guyfrancoeur

**Comment by dbrsseau** [comment]
@onwilliam tu as peut-être raison finalement... À force de retourner la question de bord à multiple reprise @joeybara et moi on a conclu qu'il faut télécharger les données `data.zip` comme dans TP1 sans modifier la commande `make data` ou `make test` puis d'utiliser les autres données `tp1-data` dans le fichier `~/depot` à l'aide de notre script. Initialement je croyais que `tp1-data.zip` remplaçait le `data.zip`.

**Comment by tannazhz** [comment]
Il me semble que c'est bien ça ! Ce sont 2 choses différentes à ne pas confondre, /data/data.txt + les autres tests présents dans tp1-data.zip
