### ISSUE TITLE
Test data3.in sur serveur Java

### ISSUE THREAD

**Issue by dychen23** [guyfrancoeur/INF3135_H2019_TP2#15]
Mes tests passent présentement sur ma machine locale, mais sur le serveur Java, le dernier test data3.in ne passe pas. Pourtant, c'est les mêmes tests.

 Est-ce quelqu'un a une idée ?

**Comment by usselsabbat** [comment]
Le dernier test est plus en rapport sur le temps t’execution.  Alors Commence par regarder la.

Tu dis que les autres tests fonctionnent, donc tes fichiers sont aux bonnes places et le script est opérationnel.

Si tu trouves rien, alors 
1) vérifie si ton avant dernière ligne s’execute correctement.

2) sinon c’est le résultat de ton nombre parfait qui est erroné pour le dernier résultat 

En espérant que ça t’aide

**Comment by dychen23** [comment]
@usselsabbat Le problème c'est que le dernier test passe sur ma machine locale, donc il trouve le nombre premier..., donc je me dis qu'il manque de quoi que je n'ai pas configurer proprement sur le serveur.

**Comment by usselsabbat** [comment]
Je comprends ce que tu dis.
Pour la direction de la configuration je ne peux malheureusement pas t'aider.

Mais si tu veux regarder au niveau du comportement du logiciel, faut te poser la question.
Pourquoi le test ne passe pas en java ?

Ne t'arrête pas au fait que ça marche sur le local pour dire que c'est la configuration.
Il se peut que cela soit justement le local qui n'est pas bon (ce que je ne souhaite pas évidement)

Mais vérifie d'abord ce qui occasionne l'erreur sur java.
- Regarde ce que le résultat de ton diff donne
- Essaye de l'executer la commande directement sur la ligne de commande $> en java

Je ne prétend pas qu'est c'est la bonne approche, mais je dis que tu gagnerais à considérer plus d'une approche.

Dans le pire des cas, tu ne ferais que prouver la solidité de ton code et justifierait un problème au niveau de la configuration.
 
bonne chance pour la suite, courage

**Comment by dychen23** [comment]
@usselsabbat Merci, je commence à regarder le problème d'une autre approche. J'ai trouvé le problem.... dans une de mes fonction de outils.c, j'ai mis pour paramètre un long tandis que dans mon outils.c c'était un unsigned long....
