### ISSUE TITLE
Code permanent dans le code.txt

### ISSUE THREAD

**Issue by Gawonou** [guyfrancoeur/INF3135_H2019_TP2#23]
Bonjour

Le code permanent dans code.txt est celui passé en argument ou celui dans le cp.txt?

**Comment by Matheus-Brum** [comment]
Le code permanent qui est produit dans code.txt est le code passé en argument. La valeur de l'argument peut venir de n'importe quelle autre commande ou fichier. J'espère que je t'ai pas mélangé.

**Comment by kaidyas21** [comment]
En plus de sortir les résultats dans stdout ou un fichier de résultats, un fichier nommé code.txt doit être produit au moment de l'exécution de votre programme et contiendra uniquement votre CODE PERMANNENT qui est passé par l'argument -c;
 Il vient de la commande apres le -c

**Comment by ahmedsalia** [comment]
Le code permanent dans code txt est le code permanent passé en argument donc le contenue de cp.txt. Mais n'oublie pas que tu peux aussi écrire les code permanent toi même en passant par le stdin

**Comment by Gawonou** [comment]
Merci les amis!
